import os

UPLOAD_FOLDER = "tmp"

SECRET_KEY = os.environ.get("SECRET_KEY")

SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_DATABASE_URI = os.environ.get("DB_STRING")

SECURITY_REGISTERABLE = True
SECURITY_PASSWORD_SALT = os.environ.get("PASSWORD_SALT")
SECURITY_SEND_REGISTER_EMAIL = False

TEMPLATES_AUTO_RELOAD = True

APP_STATE = os.environ.get("APP_STATE")
