tasks = [
    "read for at least ten minutes.",
    "go stretch.",
    "draw a picture.",
    "call someone you love.",
    "pat yourself on the shoulder.",
    "laught.",
    "sent some money to a good cause.",
    "go for a walk.",
    "close all the browser tabs you dont need.",
    "take out waste.",
    "delete old mails.",
    "drink a glass of water.",
    "disconnect for an hour.",
    "say 'I am a good person' to yourself.",
    "remember something that made you angry and let go.",
    "finish that one small task you put away for a long time.",
    "be okay with not being productive.",
    "realize that you are just a random assembly of atoms existing for a speck of time in unimaginably huge universe, and how amazing that is.",
    "try to find something you may be wrong about.",
    "say 'thank you' to someone.",
    "write a journal entry.",
    "find three things you are grateful for.",
    "cook something nice.",
    "do nothing for five minutes.",
    "stretch your neck.",
    "focus on your breathing for a moment.",
    "find something that will make you more comfortable at the moment.",
    "set your phone to 'do not disturb' or airplane mode.",
    "write four business ideas.",
    "open window.",
    "listen to music you didn't hear before.",
    "take a nap.",
    "clear your workplace.",
    "fix something in your living place.",
]
