tasks = [
    "read for at least ten minutes.",
    "go stretch.",
    "draw a picture.",
    "call someone you love.",
    "pat yourself on the shoulder.",
    "laught.",
    "sent some money to a good cause.",
    "go for a walk.",
    "close all the browser tabs you dont need.",
    "take out waste.",
    "delete old mails.",
    "drink a glass of water.",
    "disconnect for an hour.",
    "say 'I am a good person' to yourself.",
    "remember something that made you angry and let go.",
    "finish that one small task you put away for a long time.",
    "be okay with not being productive.",
    "realize that you are just a random assembly of atoms existing for a speck of time in unimaginably huge universe, and how amazing that is.",
    "try to find something you may be wrong about.",
    "say 'thank you' to someone.",
    "write a journal entry.",
    "find three things you are grateful for.",
    "cook something nice.",
    "do nothing for five minutes.",
    "stretch your neck.",
    "focus on your breathing for a moment.",
    "find something that will make you more comfortable at the moment.",
    "set your phone to 'do not disturb' or airplane mode.",
    "write four business ideas.",
    "open window.",
    "listen to music you didn't hear before.",
    "take a nap.",
    "clear your workplace.",
    "fix something in your living place.",
]

# Sources
# https://www.lesswrong.com/posts/x4GmqcwjFTnWeRiud/16-types-of-useful-predictions
predictions = [
    "predict how long a task will take you.",
    "predict how you'll feel in an upcoming situation.",
    "predict your performance on a task or goal.",
    "predict how your audience will react to a particular social media post",
    "when you try a new activity or technique, predict how much value you'll get out of it.",
    "when you make a purchase, predict how much value you'll get out of it.",
    "predict how someone will answer a question about themselves.",
    "predict how much progress you can make on a problem in five minutes.",
    "predict whether the data in your memory supports your impression.",
    "pick one expert source and predict how they will answer a question.",
    "when you meet someone new, take note of your first impressions of him. Predict how likely it is that, once you've gotten to know him better, you will consider your first impressions of him to have been accurate.",
    "predict how your Facebook friends will respond to a poll.",
    "predict how well you understand someone's position by trying to paraphrase it back to him.",
    "when you have a disagreement with someone, predict how likely it is that a neutral third party will side with you after the issue is explained to her.",
    "predict whether a surprising piece of news will turn out to be true.",
    "predict whether a quick online search will turn up any credible sources supporting a particular claim.",

]
