"""Add user secret key column

Revision ID: cbf948acdd83
Revises: dad81eb35d67
Create Date: 2020-09-29 18:45:59.853490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cbf948acdd83"
down_revision = "dad81eb35d67"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("secret_key", sa.String(length=255), nullable=True)
    )
    op.create_unique_constraint("uq_secret_key", "users", ["secret_key"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_secret_key", "users", type_="unique")
    op.drop_column("users", "secret_key")
    # ### end Alembic commands ###
