"""empty message

Revision ID: 266c632d89bd
Revises: ebc47c4a3634
Create Date: 2020-05-08 13:56:49.885023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '266c632d89bd'
down_revision = 'ebc47c4a3634'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poetry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('photo_path', sa.String(length=511), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('poezie')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poezie',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('latitude', sa.FLOAT(), nullable=True),
    sa.Column('longitude', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=255), nullable=True),
    sa.Column('photo_path', sa.VARCHAR(length=511), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('poetry')
    # ### end Alembic commands ###
