"""empty message

Revision ID: e1432f1f8f2e
Revises: 266c632d89bd
Create Date: 2020-05-09 16:51:54.333976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1432f1f8f2e'
down_revision = '266c632d89bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poetry', sa.Column('filename', sa.String(length=511), nullable=True))
    op.drop_column('poetry', 'photo_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poetry', sa.Column('photo_path', sa.VARCHAR(length=511), nullable=True))
    op.drop_column('poetry', 'filename')
    # ### end Alembic commands ###
